version: '3.0'

services: 
  app1:
    image: ${DOCKER_REGISTRY}springboot-thymeleaft
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "JAVA_OPTS=-DMEMCACHE-REDIS-NODE=redis://redis"
      - "spring.datasource.url=${JDBC_POSTGRESQL_URL}"
    ports:
     - "8080:8080"

  app2:
    image: ${DOCKER_REGISTRY}springboot-thymeleaft
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "JAVA_OPTS=-DMEMCACHE-REDIS-NODE=redis://redis"
      - "spring.datasource.url=${JDBC_POSTGRESQL_URL}"
    ports:
     - "8081:8080"

  redis:
    image: redis:4.0.11-alpine
